# -*- coding: utf-8 -*-
"""Analyzing Genetic Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LTLPKbluqYmjQkZ6fBeQlJgrmvvfz1mE
"""





from google.colab import drive
drive.mount('/content/drive')

"""# Title_ **Analyzing Genetic Code**"""

pip install biopython

"""## **Reading DNA Sequence from File**"""

def read_dna_sequence(filename):
    with open(filename, 'r') as file:
        dna_sequence = file.read().strip()  # Read the sequence and remove any leading/trailing whitespace
    return dna_sequence

# Example usage:
filename = '/content/dna_sequence.txt'
dna_sequence = read_dna_sequence(filename)
print(f"DNA Sequence: {dna_sequence}")

"""## **Calculating GC Content**"""

def calculate_gc_content(dna_sequence):
    gc_count = dna_sequence.count('G') + dna_sequence.count('C')
    total_bases = len(dna_sequence)
    gc_content = (gc_count / total_bases) * 100
    return gc_content

# Example usage:
gc_content = calculate_gc_content(dna_sequence)
print(f"GC Content: {gc_content:.2f}%")

"""## **Translating DNA Sequence into Protein Sequence**"""

from Bio.Seq import Seq

def translate_dna_to_protein(dna_sequence):
    coding_dna = Seq(dna_sequence)
    protein_sequence = coding_dna.translate()
    return protein_sequence

# Example usage:
protein_sequence = translate_dna_to_protein(dna_sequence)
print(f"Protein Sequence: {protein_sequence}")